namespace creation UI feedback for validation
StatCan/kubeflow pull request #121
Opened 2022-11-17 15:03 UTC by mathis-marcotte

closes https://github.com/StatCan/daaas/issues/769

2022-11-22 14:16 UTC, vexingly approved these changes
LGTM!

2022-11-24 14:37 UTC, chuckbelisle requested changes
juste un petite faute dans le string `registrationPage.errDuplicate`

2022-11-24 14:37 UTC, chuckbelisle commented on components/centraldashboard/public/assets/i18n/languages.json
> +            "registrationPage.errDuplicate": "L'espace de noms \"{namespace}\" existe déjà",
déjà

2022-11-24 15:25 UTC, chuckbelisle approved these changes
In dark mode, the "é" was not showing for the word.

2022-11-24 15:25 UTC, merged