Upstream master kflang
StatCan/kubeflow pull request #64
Opened 2021-08-04 14:53 UTC by rohank07

closes https://github.com/StatCan/kubeflow/issues/55

Something to think about: Do we want to merge upstream tasks into statcan/kubeflow master branch and then upstream from there or create draft PRs for upstream tasks, peer review and then send for upstreaming.

2021-08-10 16:56 UTC, wg102 requested changes

2021-08-10 16:56 UTC, wg102 commented on components/crud-web-apps/jupyter/backend/apps/common/form.py
> +        raise BadRequest("Error: the value of KF_LANG environment variable ('" + lang + "') is not a valid format (e.g 'en', 'en_US', ...)")
This message needs to be i18n. Look at how other messages are i18n within the code for help.

2021-08-10 16:56 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.html
> +            {{ v.label | translate }}
The use of the variable v, maybe a better name would be more appropriate

2021-08-10 16:56 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-advanced-options/form-advanced-options.component.scss
> +}
Add end of file newline

2021-08-10 16:56 UTC, wg102 commented on components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/form-default.component.ts
> +    }
Can it be anything else than a string? Why the verification?

2021-08-30 12:24 UTC, rohank07 commented
Closing PR. Upstream replaced ngx-translate with localize. Rather than rebasing this branch (conflicts), a new branch is created to rebase.

2021-08-30 12:24 UTC, closed without merging